language: node_js
node_js: '13'

dist: trusty
sudo: required

addons:
  chrome: stable
  apt:
    update: true
    packages:
     - dpkg
     - fluxbox

services:
  - docker

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.22.0

before_install:
  - stty cols 80
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  - export DATABASE_TEST_URL=postgres://postgres:@localhost:5432/fittrackee_test
  - export APP_SETTINGS=fittrackee_api.config.TestingConfig
  - export REACT_APP_API_URL=http://127.0.0.1
  - export NODE_ENV=development
  - export TEST_URL=http://127.0.0.1
  - export DISPLAY=:99.0
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - fluxbox >/dev/null 2>&1 &
  - docker-compose -f docker-compose-ci.yml up --build -d

script:
  - sh test.sh

after_script:
  - docker-compose down
