language: node_js
node_js: '9'

sudo: required

addons:
  apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable

services:
  - docker

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.14.0

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  - export DATABASE_TEST_URL=postgres://postgres:@localhost:5432/mpwo_test
  - export APP_SETTINGS=mpwo_api.config.TestingConfig
  - export REACT_APP_USERS_SERVICE_URL=http://0.0.0.0:5000/api/
  - export NODE_ENV=development
  - export TEST_URL=http://0.0.0.0:3000
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - docker-compose -f docker-compose-ci.yml up --build -d

script:
  - psql -c 'create database mpwo_test;' -U postgres
  - docker-compose -f docker-compose-ci.yml run api flask init_db
  - sh test.sh

after_script:
  - docker-compose down
