version: '3.3'

services:

  api-db:
    container_name: api-db
    build: https://github.com/SamR1/mpwo.git#master:mpwo_api/db
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  api:
    container_name: api
    build:
      context: https://github.com/SamR1/mpwo.git#master:mpwo_api
      dockerfile: Dockerfile-ci
    ports:
      - 5001:5000
    environment:
      - DATABASE_URL=postgres://postgres:postgres@api-db:5432/mpwo
      - DATABASE_TEST_URL=postgres://postgres:postgres@api-db:5432/mpwo_test
      - FLASK_APP=server.py
      - FLASK_DEBUG=1
      - APP_SETTINGS=mpwo_api.config.TestingConfig
    depends_on:
      - api-db
    links:
      - api-db

  client:
    container_name: client
    build:
      context: https://github.com/SamR1/mpwo.git
      dockerfile: ./mpwo_client/Dockerfile-ci
      args:
        - NODE_ENV=development
        - REACT_APP_USERS_SERVICE_URL=${REACT_APP_USERS_SERVICE_URL}
    ports:
    - 3007:3000
    depends_on:
      - api
    links:
      - api
