version: '3.3'

services:

  api-db:
    container_name: api-db
    build: ./mpwo_api/db
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  api:
    container_name: api
    build: ./mpwo_api
    ports:
      - 5001:5000
    environment:
      - DATABASE_URL=postgres://postgres:postgres@api-db:5432/mpwo
      - DATABASE_TEST_URL=postgres://postgres:postgres@api-db:5432/mpwo_test
      - FLASK_APP=server.py
      - FLASK_DEBUG=1
      - APP_SETTINGS=mpwo_api.config.DevelopmentConfig
    depends_on:
      - api-db
    links:
      - api-db

  client:
    container_name: client
    build:
      context: ./
      dockerfile: ./mpwo_client/Dockerfile
      args:
        - NODE_ENV=development
        - REACT_APP_API_URL=${REACT_APP_API_URL}
    ports:
    - 3007:3000
    depends_on:
      - api
    links:
      - api
